from pprint import pprint
from orchestrator.potential.nequip_allegro import NequIPAllegroPotential
from orchestrator.potential.kim_mixins import (enumerate_kim_repository,
                                               delete_potential_from_kim)

print("Instantiate the model from scratch")
model = NequIPAllegroPotential(
    species=['C', 'H', 'O'],
    model_type='allegro',
    device='cpu',
    cutoff_radius=4.5,
    num_layers=2,
    l_max=2,
    num_features=128,
)

# I think this should fail because the necessary files don't exist?
try:
    new_kim_id = model.save_potential_to_kim(
        'A dummy model generated during testing.')
except FileNotFoundError as e:
    print(e)
    print("It is expected that this would fail, since the model "
          "was made from scratch and never trained.")

print("Instantiating from existing files")
model = NequIPAllegroPotential.initialize_from_files(
    config_file='existing_model/config.yaml',
    compiled_file='existing_model/compiled.nequip.pth',
    parameters_file='existing_model/parameters.ckpt')

first_kim_id = model.save_potential_to_kim(
    'A dummy model generated during testing.')
print(f"Saved properly-instantiated model under new KIM ID: {first_kim_id}")

print("Loading existing KIM model")
model = NequIPAllegroPotential.initialize_from_kim(kim_id=first_kim_id)
pprint(model.hyperparameters)

print("Saving to see if version update works")
versioned_kim_id = model.save_potential_to_kim('Testing version updates.')

print("Re-loading and saving again to see if forking works")
model = NequIPAllegroPotential.initialize_from_kim(kim_id=first_kim_id)
forked_kim_id = model.save_potential_to_kim('Testing version updates.')

print("Checking repository status")
enumerate_kim_repository("nequip*")

print("Deleting stuff generated by this test")
delete_potential_from_kim(versioned_kim_id)
delete_potential_from_kim(forked_kim_id)

# Note: you have to be careful about deletion order because kimkit won't let
# you delete things that have existing newer/forked versions
delete_potential_from_kim(first_kim_id)

print("Confirming that we deleted things properly")
enumerate_kim_repository("nequip*")
