import os
from pathlib import Path
from typing import Callable, Dict, List, Literal, Optional, Union

import numpy as np
import torch
from nequip.data import AtomicDataDict, register_fields
from nequip.data.datamodule import NequIPDataModule
from nequip.data.dataset import ASEDataset
from nequip.data.stats import _MeanX
from nequip.train.ema import EMALightningModule
from omegaconf import DictConfig, ListConfig, OmegaConf
from ruamel.yaml import YAML
from torch.distributed import is_initialized

from orchestrator.storage import Storage
from orchestrator.utils.data_standard import (
    ENERGY_KEY,
    FORCES_KEY,
    FORCES_WEIGHTS_KEY,
    SELECTION_MASK_KEY,
    STRESS_KEY,
)
from orchestrator.scheduler import Scheduler

from .kim_mixins import KIMKitHandler
from .potential_base import Potential

_ATOM_ID_KEY = "global_atom_id"

# TODO: add dataclasses back in for model hyperparameters


class NequIPAllegroPotential(Potential, KIMKitHandler):
    """A wrapper for NequIP/Allegro potentials."""

    # Standardized names for potential_files used when saving/loading
    _required_files = ["config.yaml", "compiled.nequip.pth"]
    _optional_files = ["parameters.ckpt"]

    # KIM stuff
    _potential_type = "nequip/allegro"
    # _model_type set in init
    _model_definition = None
    _model_driver = None
    _kim_item_type = "simulator-model"

    _kim_api_version: str = "kim-api-not-supported-for-this-model"
    _kim_simulator_name: str = "lammps"

    def __init__(
        self,
        species: list[str],
        model_type: Optional[Literal["nequip", "allegro"]] = None,
        device: Literal["cpu", "cuda"] = "cpu",
        cutoff_radius: float = 4.5,
        num_layers: int = 1,
        l_max: int = 1,
        num_features: int = 64,
        potential_name: str = "nequip_allegro",
        template: Optional[str] = None,
        **kwargs,
    ):
        """Initialization of the potential.

        :param species: list of strings containing element symbols
        :type species: list[str]
        :param model_type: "nequip" or "allegro"
        :type model_type: str
        :param config_file: config.yaml file to use as a template. The values
            in this file will be overloaded by those provided to this class
            constructor (e.g., l_max, num_features, ...). Required for
            save/load.
        :type config_file: str
        :param compiled_file: Compiled model generated by `nequip-compile`.
            Must end in ".pth" or ".pt2". Required for save/load.
        :type compiled_file: str
        :param parameters_file: PyTorch model file containing model parameters.
            Usually something like `last.ckpt` or `best.ckpt`.
        :type parameters_file: str
        :param cutoff_radius: cutoff range for computing local neighborhoods.
        :type cutoff_radius: float
        :param num_layers: the number of layers in a NequIP model, or the body
            order of an Allegro model (1=3-body, 2=4-body, ...).
        :type num_layers: int
        :param l_max: the maximum order to use when computing spherical
            harmonics.
        :type l_max: int
        :param num_features: dimensionality of latent features.
        :type num_features: int
        :param potential_name: Name of the potential, used as filename prefix
        :type potential_name: str
        :param potential_files: list of all files that should be associated
            with the potential, such as parameter files, training files, or
            additional metadata files. These are optional and may be updated by
            the .train() function.
        :type potential_files: list[str]
        :param template: Optional config.yaml file from which to load the
            model. Note that if the template does NOT set one of the required
            hyperparameters, default values specified in the signature of this
            function will be used.
        :type template: str
        """
        super().__init__(
            species=species,
            potential_name=potential_name,
            template=template,
            **kwargs,
        )

        # Used for tracking what to copy during save/load
        self.potential_files = {
            "config.yaml": None,
            "compiled.nequip.pth": None,
            "parameters.ckpt": None,
        }

        self.model_type = model_type
        self._model_type = model_type  # set internal version for KIM stuff

        if template is None:
            # Need to provide all required hyperparameters
            self.hyperparameters = {
                "species": species,
                "model_type": model_type,
                "device": device,
                "cutoff_radius": cutoff_radius,
                "l_max": l_max,
                "num_layers": num_layers,
                "num_features": num_features,
            }

        else:
            self.hyperparameters = self._load_hparams_from_config(
                template,
                defaults={
                    "species": species,
                    "model_type": model_type,
                    "device": device,
                    "cutoff_radius": cutoff_radius,
                    "l_max": l_max,
                    "num_layers": num_layers,
                    "num_features": num_features,
                },
            )

    @classmethod
    def initialize_from_files(
        cls,
        config_file: str,
        compiled_file: str = None,
        parameters_file: str = None,
    ) -> Potential:
        """Initialize the potential from a YAML file.

        Optionally also load the compiled model and parameters files).

        :param config_file: The NequIP/Allegro configuration file (e.g.,
            config.yaml)
        :param compiled_file: The compiled model generated using nequip-compile
        :param parameters_file: The raw model paramaters (e.g., best.ckpt)
        """
        hparams = cls._load_hparams_from_config(config_file)

        instance = cls(**hparams)

        instance.potential_files = {
            "config.yaml": config_file,
            "compiled.nequip.pth": compiled_file,
            "parameters.ckpt": parameters_file,
        }

        return instance

    @classmethod
    def initialize_from_kim(cls, kim_id: str) -> Potential:
        """Initialize model from an existing potential in the KIM repo.

        :param kim_id: The KIM ID of the saved potential (e.g.,
            nequip_allegro__SM_...)
        """
        instance = super().initialize_from_kim(kim_id)

        config_file = os.path.join(kim_id, "config.yaml")
        compiled_file = os.path.join(kim_id, "compiled.nequip.pth")
        parameters_file = os.path.join(kim_id, "parameters.ckpt")

        instance.hyperparameters = instance._load_hparams_from_config(
            config_file)

        # Make sure to set the instance variable too
        instance.model_type = instance.hyperparameters["model_type"]
        instance._model_type = instance.model_type

        instance.potential_files = {
            "config.yaml":
            config_file,
            "compiled.nequip.pth":
            compiled_file,
            "parameters.ckpt":
            parameters_file if os.path.exists(parameters_file) else None,
        }

        return instance

    @staticmethod
    def _load_hparams_from_config(config_path, defaults=None):
        """Parses a config file to extract the key hyperparameters.

        :param config_file: The NequIP/Allegro configuration file (e.g.,
            config.yaml)
        :param defaults: Default values to use if not provided in config file.
        """
        if defaults is None:
            defaults = {}

        yaml = YAML()
        yaml.preserve_quotes = True

        with open(config_path, "r") as f:
            config = yaml.load(f)

        # Try to load expected hyperparameters
        hparams = {}

        key_mapping = {
            "cutoff_radius": "cutoff_radius",
            "num_features": "num_scalar_features",
            "num_layers": "training_module.model.num_layers",
            "l_max": "training_module.model.l_max",
            "model_type": "training_module.model._target_",
            "device": "trainer.accelerator",
            "species": "model_type_names",
        }

        def get_nested_value(d: dict, nested_key: str):
            """Set a value in a nested dictionary using dot notation."""
            keys = nested_key.split(".")
            for key in keys[:-1]:
                d = d[key]
            return d[keys[-1]]

        for our_key, their_key in key_mapping.items():
            try:
                key_value = get_nested_value(config, their_key)
                if key_value == '<will_be_set_by_orchestrator>':
                    raise KeyError('template has unset values')
                hparams[our_key] = get_nested_value(config, their_key)
            except KeyError as e:
                try:
                    hparams[our_key] = defaults[our_key]
                except KeyError:
                    raise RuntimeError(
                        f"Could not find key `{our_key}` in expected field "
                        f"`{their_key}` or in `defaults` dictionary. Are you "
                        "sure your YAML file is formatted correctly?") from e

        # Rename some stuff
        if hparams["device"] == "gpu":
            hparams["device"] = "cuda"

        if hparams["model_type"] == "nequip.model.NequIPGNNModel":
            hparams["model_type"] = "nequip"
        elif hparams["model_type"] == "allegro.model.AllegroModel":
            hparams["model_type"] = "allegro"
        else:
            raise ValueError(
                f"Unexpected model_type: `{hparams['model_type']}`")

        return hparams

    def _initialize_calculator(self):
        """Initialize ASE calculator and update self._potential_calculator."""

        from nequip.integrations.ase import NequIPCalculator

        self._potential_calculator = NequIPCalculator.from_compiled_model(
            self.potential_files["compiled.nequip.pth"],
            device=self.hyperparameters["device"],
        )

    def load_potential(self, path: str):
        """Loads model hyperparams from directory written by save_potential().

        Note that if you are trying to create a new potential
        using files that were created with a tool outside of
        the Orchestrator, you should likely just use __init__().

        Required contents of `path`:
            - config.yaml (the YAML file used by external nequip-* tools)
            - compiled.nequip.pth (the compiled version of the model)

        Optional contents of `path`:
            - parameters.ckpt (the raw output of a training run)
        """

        config_path = os.path.abspath(os.path.join(path, "config.yaml"))
        compile_path = os.path.abspath(
            os.path.join(path, "compiled.nequip.pth"))
        # Point to the new path and the default file names.
        self.potential_files = {
            "config.yaml": config_path,
            "compiled.nequip.pth": compile_path,
        }
        # Ensure that the specified path contains all of the required files,
        # with the expected names
        _ = self._check_files_set_and_exist(check_exist=True)

        # Load the config.yaml file and extract the main hyperparameters
        hparams = self._load_hparams_from_config(config_path)
        # Save the new hyperparameters
        self.hyperparameters = hparams

        # Also check the optional files
        params_path = os.path.join(path, "parameters.ckpt")
        if os.path.exists(params_path):
            self.potential_files["parameters.ckpt"] = os.path.abspath(
                params_path)

    def _write_hparams_to_file(self, path: str):
        """Writes the current model hyperparameters to a config.yaml file."""

        # Write the config.yaml file
        yaml = YAML()
        yaml.preserve_quotes = True

        if self.potential_files["config.yaml"] is not None:
            # Use the user-provided template
            source_file = self.potential_files["config.yaml"]
        else:
            # Use the hard-coded template
            source_file_location = os.path.dirname(os.path.abspath(__file__))
            source_file = (f"{source_file_location}/default_templates/"
                           f"{self.model_type}.yaml")

        with open(source_file, "r") as f:
            config = yaml.load(f)

        config["model_type_names"] = self.species
        config["chemical_species_to_atom_type_map"] = {
            k: k
            for k in self.species
        }

        if self.model_type == "nequip":
            config["training_module"]["model"]["_target_"] = (
                "nequip.model.NequIPGNNModel")
        elif self.model_type == "allegro":
            config["training_module"]["model"]["_target_"] = (
                "allegro.model.AllegroModel")
        else:
            raise ValueError(f"Unexpected model_type: `{self.model_type}`")

        if self.hyperparameters["device"] == "gpu":
            config["training_module"]["model"]["compile_mode"] = "compile"

        # Define mapping from hyperparameter keys to config paths
        field_mapping = {
            "cutoff_radius": "cutoff_radius",
            "num_features": "num_scalar_features",
            "num_layers": "training_module.model.num_layers",
            "l_max": "training_module.model.l_max",
            # "dataset_file_path": "data.split_dataset.file_path",
            # "train_frac": "data.split_dataset.train",
            # "test_frac": "data.split_dataset.test",
            # "val_frac": "data.split_dataset.val",
            # "max_epochs": "trainer.max_epochs",
            "device": "trainer.accelerator",
            # "batch_size": "data.train_dataloader.batch_size",
            # "energy_weight": "training_module.loss.coeffs.total_energy",
            # "force_weight": "training_module.loss.coeffs.forces",
            # "lr": "training_module.optimizer.lr",
            # "lr_scheduler_patience":
            # "training_module.lr_scheduler.scheduler.patience",
        }

        def set_nested_value(d: dict, path: str, value):
            """Set a value in a nested dictionary using dot notation."""
            keys = path.split(".")
            for key in keys[:-1]:
                if key not in d:
                    d[key] = {}
                d = d[key]
            d[keys[-1]] = value

        full_hyperparameters = self.hyperparameters

        # Overload only the fields present in hyperparameters
        for hyperparam_key, value in full_hyperparameters.items():
            if hyperparam_key in field_mapping:
                config_path = field_mapping[hyperparam_key]
                set_nested_value(config, config_path, value)

        new_config_file = os.path.join(path, "config.yaml")
        with open(new_config_file, "w") as f:
            # Save updated YAML file
            yaml.dump(config, f)

        return new_config_file

    def save_potential(
        self,
        path: str,
        makedirs: bool = False,
    ) -> Union[str, list[str]]:
        """Save the potential and other necessary data to disk.

        This function saves the config.yaml file, overwriting it with the
        current hyperparameters. It also calls `nequip-compile` to save the
        compiled version of the model.

        New contents of `path`:
            - config.yaml (the YAML file used by external nequip-* tools)
            - compiled.nequip.pth (the compiled version of the model)

        Optional contents of `path`:
            - parameters.ckpt (the raw output of a training run)

        :param path: Directory path where the model should be saved
        :param makedirs: If True, creates folder if it doesn't exist. Default
            is False.
        :returns: List of paths to the saved model files
        """

        # NOTE: don't need to check that potential_files has been set, since
        # they'll be generated by this function
        # self._check_files_set_and_exist(check_exist=False)

        if makedirs:
            os.makedirs(path, exist_ok=True)
        elif not os.path.isdir(path):
            raise FileNotFoundError(f"Directory not found: {path}")

        new_config_file = self._write_hparams_to_file(path)

        self.potential_files["config_file"] = new_config_file

        # Write the parameters.ckpt, which should just copy over the provided
        # file. Note that this is not required to exist
        new_compiled_file = os.path.join(path, "compiled.nequip.pth")

        if self.potential_files["compiled.nequip.pth"] is None:
            # Need to compile the model
            # Already confirmed that parameters_files is not also none

            if self.potential_files["parameters.ckpt"] is None:
                raise FileNotFoundError(
                    "self.potential_files['compiled.nequip.pth'] and "
                    "self.potential_files['parameters.ckpt'] cannot both be "
                    "None when calling save_potential. "
                    "You probably need to train your model first using "
                    ".train() or .submit_train()")

            import subprocess

            command = [
                "nequip-compile",
                self.potential_files["parameters.ckpt"],
                new_compiled_file,
                "--mode",
                "torchscript",
                "--device",
                self.hyperparameters["device"],
            ]

            try:
                # Execute the command
                subprocess.run(command,
                               check=True,
                               capture_output=True,
                               text=True)

            except subprocess.CalledProcessError as e:
                print(f"An error occurred during nequip-compile:\n{e.stderr}")
                raise
        else:
            # Compiled file already exists, just need to copy
            import shutil

            shutil.copyfile(self.potential_files["compiled.nequip.pth"],
                            new_compiled_file)

        self.potential_files["config.yaml"] = new_config_file
        self.potential_files["compiled.nequip.pth"] = new_compiled_file

        if self.potential_files["parameters.ckpt"] is not None:
            # If provided, copy over the parameters as well.
            new_params_file = os.path.join(path, "parameters.ckpt")

            import shutil

            shutil.copyfile(self.potential_files["parameters.ckpt"],
                            new_params_file)

            self.potential_files["parameters.ckpt"] = new_params_file

    def load_from_submitted_training(
        self,
        calc_id: Union[str, int],
        scheduler: Scheduler,
    ):
        """Update model hyperparameters using the results from .submit_train().

        This method waits for the training job to complete (if it hasn't
        already) and then loads the trained potential files from the job's
        output directory. It uses the load_potential method to initialize the
        SNAP potential from the trained files.

        :param calc_id: The calculation ID returned by submit_train
        :type calc_id: Union[str, int]
        :param scheduler: Scheduler object used to manage the job
        :type scheduler: Scheduler
        :return: None
        """
        scheduler.block_until_completed(calc_id)

        path = Path(scheduler.get_job_path(calc_id)).resolve()

        config_file = path / "config.yaml"
        parameters_file = self.find_newest_best_ckpt(path).resolve()
        compiled_file = path / "compiled.nequip.pth"

        if not compiled_file.exists():
            # Need to compile the model
            # Already confirmed that parameters_files is not also none

            if not parameters_file.exists():
                raise RuntimeError(f"Could not find file: `{parameters_file}`")

            import subprocess

            command = [
                "nequip-compile",
                # self.potential_files["parameters.ckpt"],
                parameters_file,
                compiled_file,
                "--mode",
                "torchscript",
                "--device",
                self.hyperparameters["device"],
            ]

            try:
                # Execute the command
                subprocess.run(command,
                               check=True,
                               capture_output=True,
                               text=True)

            except subprocess.CalledProcessError as e:
                print(f"An error occurred during nequip-compile:\n{e.stderr}")
                raise

        self.hyperparameters = self._load_hparams_from_config(config_file)

        self.potential_files = {
            "config.yaml": config_file,
            "compiled.nequip.pth": compiled_file,
            "parameters.ckpt": parameters_file,
        }

    @staticmethod
    def find_newest_best_ckpt(root: Union[str, Path]) -> Optional[Path]:
        """Find the newest checkpoint file.

        Searches outputs/<YYYY-MM-DD>/<HH-MM-SS>/**/best.ckpt under `root`.

        Returns a Path to best.ckpt, or None if not found.
        """
        from pathlib import Path

        root = Path(root)

        candidates = []
        outputs = root / "outputs"
        if not outputs.is_dir():
            return None

        for date_dir in outputs.iterdir():
            if not date_dir.is_dir():
                continue
            for time_dir in date_dir.iterdir():
                if not time_dir.is_dir():
                    continue
                for ckpt in time_dir.rglob("best.ckpt"):
                    if ckpt.is_file():
                        candidates.append((date_dir.name, time_dir.name, ckpt))

        if not candidates:
            return None

        # Lexicographic sort works for zero-padded "YYYY-MM-DD" and "HH-MM-SS"
        candidates.sort(key=lambda x: (x[0], x[1]))
        return candidates[-1][2]

    def train(
        self,
        dataset_list: list[str],
        storage: Storage,
        scheduler: Optional[Scheduler],
        energy_weight: float = 1.0,
        force_weight: float = 1.0,
        stress_weight: float = 0.0,
        train_frac: float = 0.8,
        test_frac: float = 0.1,
        val_frac: float = 0.1,
        per_atom_weights: Union[str, list[np.ndarray]] = None,
        log_errors: bool = False,
        max_epochs: int = 100,
        batch_size: int = 2,
        lr: float = 0.001,
        lr_scheduler_patience: int = 10,
        # TODO: add ltau/error logging support via kwargs
        **kwargs,
    ) -> tuple[str, float]:
        """Train the potential using the provided data.

        :param dataset_list: list of dataset handles to use for training
        :type dataset_list: list[str]
        :param storage: Storage object to access training data
        :type storage: Storage
        :param scheduler: Scheduler object for job management
        :type scheduler: Scheduler
        :param energy_weight: Weight for energy terms in the loss function
        :type energy_weight: float
        :param force_weight: Weight for force terms in the loss function
        :type force_weight: float
        :param stress_weight: Weight for stress terms in the loss function
        :type stress_weight: float
        :param train_frac: Fraction of data to use for training
        :type train_frac: float
        :param test_frac: Fraction of data to use for testing
        :type test_frac: float
        :param val_frac: Fraction of data to use for validating
        :type val_frac: float
        :param per_atom_weights: Controls per-atom weighting
        :type per_atom_weights: Union[str, list[np.ndarray]]
        :param log_errors: Record the per-atom errors at each training epoch.
        :param max_epochs: Maximum number of training epochs. Default is 100
        :param batch_size: Training batch size. Default is 2
        :param lr: Step size scaling factor when applying gradient updates.
            Default is 0.001
        :param lr_scheduler_patience: Number of epochs to wait before
            decreasing step size. Default is 10.
        :param kwargs: Additional potential-specific training parameters

        :returns: Tuple containing (path? to trained potential, training error)
        :rtype: tuple[str, float]
        """

        work_dir = ("." if scheduler is None else scheduler.make_path(
            self.__class__.__name__, "training"))
        abs_work_dir = os.path.abspath(work_dir)  # nequip-train gets confused

        self._write_training_script(
            abs_work_dir,
            storage,
            dataset_list,
            scheduler,
            train_frac,
            test_frac,
            val_frac,
            energy_weight,
            force_weight,
            stress_weight,
            per_atom_weights,
            # apply_mask,
            log_errors,
            max_epochs,
            batch_size,
            lr,
            lr_scheduler_patience,
        )

        # Need to compile the model
        # Already confirmed that parameters_files is not also none

        # Move into scheduler execution dir manually since YAML doesn't let you
        # specify the output directory
        cwd = os.getcwd()
        os.chdir(work_dir)

        import subprocess

        command = [  # Note: will need to specify -cp when doing submit_train
            "nequip-train",
            "-cn",
            "config.yaml",
        ]

        try:
            # Execute the command
            subprocess.run(
                command,
                check=True,
                # capture_output=True,
                # text=True
            )
            os.chdir(cwd)

            config_file = os.path.join(abs_work_dir, "config.yaml")
            parameters_file = self.find_newest_best_ckpt(
                abs_work_dir).resolve()

            self.potential_files = {
                "config.yaml": config_file,
                "compiled.nequip.pth": None,  # haven't compiled new model yet
                "parameters.ckpt": parameters_file,
            }

        except subprocess.CalledProcessError as e:
            os.chdir(cwd)
            raise RuntimeError(
                "An error occurred during nequip-train. If it's a libmpi.so "
                "issue, try doing "
                "`export LD_LIBRARY_PATH=$CRAY_MPICH_DIR/lib:$LD_LIBRARY_PATH`"
            ) from e

        return abs_work_dir, 0.0

    def submit_train(
        self,
        dataset_list: list[str],
        storage: Storage,
        scheduler: Scheduler,
        job_details: dict,
        energy_weight: float = 1.0,
        force_weight: float = 1.0,
        stress_weight: float = 0.0,
        train_frac: float = 0.8,
        test_frac: float = 0.1,
        val_frac: float = 0.1,
        per_atom_weights: Union[str, list[np.ndarray]] = None,
        log_errors: bool = False,
        max_epochs: int = 100,
        batch_size: int = 2,
        lr: float = 0.001,
        lr_scheduler_patience: int = 10,
        **kwargs,
    ) -> Union[str, int]:
        """Train the potential using the provided data via a submitted job.

        :param dataset_list: list of dataset handles to use for training
        :type dataset_list: list[str]
        :param storage: Storage object to access training data
        :type storage: Storage
        :param scheduler: Scheduler object for job management
        :type scheduler: Scheduler
        :param job_details: information controlling job submission
        :type job_details: dict
        :param energy_weight: Weight for energy terms in the loss function
        :type energy_weight: float
        :param force_weight: Weight for force terms in the loss function
        :type force_weight: float
        :param stress_weight: Weight for stress terms in the loss function
        :type stress_weight: float
        :param train_frac: Fraction of data to use for training
        :type train_frac: float
        :param test_frac: Fraction of data to use for testing
        :type test_frac: float
        :param val_frac: Fraction of data to use for validation
        :type val_frac: float
        :param per_atom_weights: Controls per-atom weighting
        :type per_atom_weights: Union[str, list[np.ndarray]]
        :param log_errors: Record the per-atom errors at each training epoch.
        :param max_epochs: Maximum number of training epochs. Default is 100
        :param batch_size: Training batch size. Default is 2
        :param lr: Step size scaling factor when applying gradient updates.
            Default is 0.001
        :param lr_scheduler_patience: Number of epochs to wait before
            decreasing step size. Default is 10.
        :param kwargs: Additional potential-specific training parameters

        :returns: Tuple containing (path? to trained potential, training error)
        :rtype: tuple[str, float]
        """

        work_dir = scheduler.make_path(self.__class__.__name__, ".")

        cwd = os.getcwd()
        os.chdir(work_dir)
        self._write_training_script(
            ".",  # so that the internal paths are correct relative to work_dir
            storage,
            dataset_list,
            scheduler,
            train_frac,
            test_frac,
            val_frac,
            energy_weight,
            force_weight,
            stress_weight,
            per_atom_weights,
            log_errors,
            max_epochs,
            batch_size,
            lr,
            lr_scheduler_patience,
        )
        os.chdir(cwd)

        abs_work_dir = os.path.abspath(work_dir)  # nequip-train gets confused
        command = f"nequip-train -cp {abs_work_dir} -cn config.yaml"

        calc_id = scheduler.submit_job(
            command=command,
            run_path=work_dir,
            job_details=job_details,
        )
        return calc_id

    def _write_training_script(
        self,
        path_type: str,
        storage: Storage,
        dataset_list: list,
        scheduler: Scheduler,
        train_frac: float = 0.8,
        test_frac: float = 0.1,
        val_frac: float = 0.1,
        energy_weight: float = 1.0,
        force_weight: float = 1.0,
        stress_weight: float = 0.0,
        per_atom_weights: Union[str, list[np.ndarray]] = None,
        log_errors: bool = False,
        max_epochs: int = 100,
        batch_size: int = 2,
        lr: float = 0.001,
        lr_scheduler_patience: int = 10,
        # apply_mask: bool = False,
    ):
        """Writes the config.yaml file used by nequip-train.

        This function allows overloading commonly used values, and prepares the
        model for use with per-environment ("per-atom") force weighting and
        error logging for use with the LTAU UQ module.

        :param path_type: directory in which to run submitted job
        :type path_type: str
        :param storage: storage module
        :type storage: Storage
        :param dataset_list: list of dataset handles to train to. Will be
            concatenated then randomly split for train/test/val.
        :type dataset_list: list
        :param scheduler: the scheduler for managing path definition and job
            submission, if none are supplied, will use the default scheduler
            defined in this class
        :type scheduler: Scheduler
        :param val_frac: Fraction of configurations to use for validation split
        :type val_frac: float
        :param energy_weight: weight of energy data in the loss function
        :type energy_weight: float
        :param force_weight: weight of the force data in the loss function
        :type force_weight: float
        :param stress_weight: weight of the stress data in the loss function
        :type stress_weight: float
        :param per_atom_weights: can be a string or a list of weights. If a
            string, it should be a path to a .npz file, where each array in
            .files is the weight array for a given configuration and the
            ordering of the arrays is assumed to be the same as the order of
            the configurations in the dataset. If a list of arrays, it should
            be the same format as what would be loaded off of the .npz file.
        :type per_atom_weights: str or list
        :param log_errors: If True, record the per-sample errors at each epoch.
        :param max_epochs: Maximum number of training epochs. Default is 100
        :param batch_size: Training batch size. Default is 2
        :param lr: Step size scaling factor when applying gradient updates.
            Default is 0.001
        :param lr_scheduler_patience: Number of epochs to wait before
            decreasing step size. Default is 10.
        """

        import itertools
        import warnings

        from ase.io import write
        from torch.utils.data import random_split

        # Write the initial config file
        config_file = self._write_hparams_to_file(path_type)

        # Now add the provided trainer hyperparameters
        yaml = YAML()
        yaml.preserve_quotes = True  # Preserve quotes if they exist

        with open(config_file, "r") as f:
            config = yaml.load(f)

        # Override fields in config file
        loss_dict = {
            "_target_":
            "nequip.train.MetricsManager",
            "metrics": [
                {
                    "name": "forces_weighted_loss",
                    "coeff": force_weight,
                    "metric": {
                        "_target_":
                        "orchestrator.potential.nequip_allegro.WeightedLoss"
                    },
                },
                {
                    "name": "total_energy_mae",
                    "field": "total_energy",
                    "coeff": energy_weight,
                    "metric": {
                        "_target_": "nequip.train.MeanAbsoluteError",
                    },
                },
            ],
        }
        if stress_weight > 0:
            loss_dict["metrics"].append({
                "name": "stress_mae",
                "field": "stress",
                "coeff": stress_weight,
                "metric": {
                    "_target_": "nequip.train.MeanAbsoluteError",
                },
            })

        config["training_module"]["loss"] = loss_dict
        config["trainer"]["max_epochs"] = max_epochs
        config["data"]["train_dataloader"]["batch_size"] = batch_size
        config["training_module"]["optimizer"]["lr"] = lr
        config["training_module"]["lr_scheduler"]["lr_scheduler_patience"] = (
            lr_scheduler_patience)

        # Need to download datasets and save to XYZ
        if not isinstance(dataset_list, list):
            dataset_list = [dataset_list]

        full_dataset = []
        for dataset_handle in dataset_list:
            configs = storage.get_data(dataset_handle)
            full_dataset.extend(configs)

        # Prepare for per-atom weighted training
        config["data"]["_target_"] = (
            "orchestrator.potential.nequip_allegro.ASEDataModuleWithID")

        if "include_keys" not in config["data"]:
            config["data"]["include_keys"] = [FORCES_WEIGHTS_KEY]
        elif FORCES_WEIGHTS_KEY not in config["data"]["include_keys"]:
            config["data"]["include_keys"] += [FORCES_WEIGHTS_KEY]

        _atom_counter = 0
        for atoms in full_dataset:
            if FORCES_WEIGHTS_KEY not in atoms.arrays:
                atoms.arrays[FORCES_WEIGHTS_KEY] = np.ones(len(atoms))

            atoms.arrays[_ATOM_ID_KEY] = np.arange(_atom_counter,
                                                   _atom_counter + len(atoms))

            _atom_counter += len(atoms)

        # Even if additional per-atom weights aren't used, this should be
        # the monitored metric
        config["monitored_metric"] = "train_loss_epoch/forces_weighted_loss"

        if SELECTION_MASK_KEY in full_dataset[0].info:
            warnings.warn(
                f"Dataset contains `{SELECTION_MASK_KEY}` key;"
                " atom masking is being applied.",
                stacklevel=1,
            )
            # Overload existing weights arrays
            for atoms in full_dataset:
                atoms.arrays[FORCES_WEIGHTS_KEY] *= atoms.arrays[
                    SELECTION_MASK_KEY]

        if per_atom_weights is not None:
            config[
                "monitored_metric"] = "train_loss_epoch/forces_weighted_loss"

            if isinstance(per_atom_weights, list):
                # Attach to each
                # *= so you don't overwrite the selection mask
                for atoms, weights in zip(full_dataset,
                                          per_atom_weights,
                                          strict=True):
                    assert len(atoms) == len(weights), (
                        f"Per-atom weight array length ({len(weights)}) does "
                        f"not match atoms length ({len(atoms)}). Maybe they "
                        "were provided in the wrong order?")
                    atoms.arrays[FORCES_WEIGHTS_KEY] *= weights
            elif isinstance(per_atom_weights, str):
                # Rename key
                # *= so you don't overwrite the selection mask
                npzfile = np.load(per_atom_weights)  # .npz file
                per_atom_weights = [npzfile[name] for name in npzfile.files]

                for atoms, weights in zip(full_dataset,
                                          per_atom_weights,
                                          strict=True):
                    assert len(atoms) == len(weights), (
                        f"Per-atom weight array length ({len(weights)}) does "
                        f"not match atoms length ({len(atoms)}). Maybe they "
                        "were provided in the wrong order?")
                    atoms.arrays[FORCES_WEIGHTS_KEY] *= weights
            else:
                raise TypeError(
                    f"Unexpected type of `{type(per_atom_weights)}`. "
                    "Must be list (of numpy arrays) or string.")

        # Rename keys to values expected by nequip code
        for atoms in full_dataset:
            if ENERGY_KEY in atoms.info:
                atoms.info["energy"] = atoms.info[ENERGY_KEY]
            if FORCES_KEY in atoms.arrays:
                atoms.arrays["forces"] = atoms.arrays[FORCES_KEY]
            if STRESS_KEY in atoms.info:
                # Note: ASE needs "stress" to be an array
                atoms.info["stress"] = np.array(atoms.info[STRESS_KEY])

        species = list(
            set(
                itertools.chain.from_iterable(
                    [atoms.get_chemical_symbols() for atoms in full_dataset])))

        if log_errors:
            # Optionally also add LTAU modules to custom file
            training_module_target = config["training_module"]["_target_"]
            if "EMALightningModule" not in training_module_target:
                warnings.warn(
                    f"Overriding {training_module_target} with "
                    "EMALightningModule. "
                    "The current custom module used for error logging inherits"
                    " from EMALightningModule. If you want to use a different"
                    " module, you will need to implement a new class similar "
                    "to LTAULightningModule in this file.",
                    stacklevel=1,
                )

            # Use custom modules for error logging
            config["training_module"]["_target_"] = (
                "orchestrator.potential.nequip_allegro.LTAULightningModule")
            err_save_dir = "${hydra:runtime.output_dir}/${trainer.logger.name}"
            config["training_module"]["error_save_dir"] = err_save_dir
            config["data"]["_target_"] = (
                "orchestrator.potential.nequip_allegro.ASEDataModuleWithID")

            if "global_atom_id" not in config["data"]["include_keys"]:
                config["data"]["include_keys"] += [_ATOM_ID_KEY]

        config["model_type_names"] = species
        config["chemical_species_to_atom_type_map"] = {k: k for k in species}

        save_path = path_type
        save_file = os.path.join(save_path, "config.yaml")

        assert train_frac > 0, "`train_frac` must be > 0"
        assert test_frac >= 0 and test_frac < 1, "`test_frac` must be in (0,1)"
        assert val_frac >= 0 and val_frac < 1, "`val_frac` must be in (0,1)"

        total_size = len(full_dataset)
        if val_frac > 0:
            val_len = max(1, int(val_frac * total_size))
        if test_frac > 0:
            test_len = max(1, int(test_frac * total_size))

        # 3. Assign the remainder to train to ensure they sum to total_size
        train_len = total_size - val_len - test_len

        train, test, val = random_split(full_dataset,
                                        [train_len, test_len, val_len])

        del config["data"]["train_file_path"]
        del config["data"]["test_file_path"]
        del config["data"]["val_file_path"]

        train_dataset_path = os.path.join(save_path, "training_set.xyz")
        write(train_dataset_path, train, format="extxyz")
        config["data"]["train_file_path"] = train_dataset_path

        if test_len > 0:
            test_dataset_path = os.path.join(save_path, "testing_set.xyz")
            write(test_dataset_path, test, format="extxyz")
            config["data"]["test_file_path"] = test_dataset_path

        if val_len > 0:
            val_dataset_path = os.path.join(save_path, "validation_set.xyz")
            write(val_dataset_path, val, format="extxyz")
            config["data"]["val_file_path"] = val_dataset_path

        with open(save_file, "w") as f:
            # Save updated YAML file
            yaml.dump(config, f)

        self.logger.info(f"Saving updated config file to {save_file}")

    def get_lammps_commands(self) -> str:
        """
        Extract required commands to inject into a LAMMPS input file to
        enable using external NequIP/Allegro potentials with a direct
        LAMMPS interface.

        :returns: Commands to inject into a LAMMPS input file to directly
            run a LAMMPS simulation with an external NequIP/Allegro potential
        :rtype: str
        """
        from pathlib import Path

        # Determine path of compiled model file
        if not self.potential_files:
            raise ValueError(
                "potential_files is not set on this Potential instance")
        model_path_str = self.potential_files.get("compiled.nequip.pth")
        if not model_path_str:
            raise ValueError(
                'Missing "compiled.nequip.pth" in potential_files.')
        model_path = Path(model_path_str).expanduser().resolve()

        if not model_path.is_file():
            raise FileNotFoundError(
                f"compiled.nequip.pth not found at: {model_path}")

        model_type = getattr(self, "model_type", None)
        if model_type not in ["nequip", "allegro"]:
            raise ValueError(
                f"Expected model_type to be 'nequip' or 'allegro', "
                f"got: {model_type}")

        if not hasattr(self, "species") or not self.species:
            raise ValueError(
                "Species list is not set on this Potential instance")

        species_str = " ".join(self.species)
        model_str = model_path.as_posix()

        return (f"pair_style {model_type}\n"
                f"pair_coeff * * {model_str} {species_str}")


class WeightedLoss(_MeanX):
    """Custom loss function for using per-atom weights to the loss function."""

    def __init__(self, **kwargs):
        """Initialize."""
        # Remove modifier since we'll handle the computation manually
        super().__init__(modifier=torch.nn.Identity(), **kwargs)

    def update(self, preds: torch.Tensor, target: torch.Tensor) -> None:
        """Update method expected by torchmetrics and MetricsManager."""
        # This should receive the weighted loss values
        super().update(preds - target)  # This will be overridden below

    def __call__(
        self,
        preds: AtomicDataDict.Type,
        ref: AtomicDataDict.Type,
    ):
        """Compute the loss."""

        # TODO: add energy weighting

        weight = ref[FORCES_WEIGHTS_KEY]
        pred_fcs = preds["forces"]
        ref_fcs = ref["forces"]

        # Compute weighted absolute errors for each sample
        weighted_errors = (pred_fcs - ref_fcs).abs() * weight[:, None]

        # Update the internal state for epoch-level computation
        # Flatten the weighted errors to treat each force component as a sample
        self.update_weighted(weighted_errors.flatten())

        # Return the mean for the current batch (for per-step logging)
        return weighted_errors.mean()

    def update_weighted(self, weighted_errors: torch.Tensor) -> None:
        """Custom update method for weighted errors."""
        sample_count = weighted_errors.numel()
        if sample_count > 0:
            weighted_errors = weighted_errors.to(self.sum.dtype)
            # Update sum and count for epoch-level computation
            self.sum = self.sum + weighted_errors.sum()
            self.count = self.count + sample_count

    def __str__(self):
        """String representation."""
        return "forces_weighted_loss"


class ASEDatasetWithGlobalIDs(ASEDataset):
    """ASEDataset subclass that assigns globally unique atom IDs."""

    _global_counter = 0  # Class-level counter shared across all datasets

    def __init__(
        self,
        file_path: str,
        transforms: List[Callable] = None,
        ase_args: Dict[str, any] = None,
        include_keys: Optional[List[str]] = None,
        exclude_keys: Optional[List[str]] = None,
        key_mapping: Optional[Dict[str, str]] = None,
    ):
        """Initialize."""

        # Set mutable defaults
        if transforms is None:
            transforms = []

        if ase_args is None:
            ase_args = {}

        if include_keys is None:
            include_keys = []

        if exclude_keys is None:
            exclude_keys = []

        if key_mapping is None:
            key_mapping = {}

        register_fields(node_fields=[_ATOM_ID_KEY, FORCES_WEIGHTS_KEY])

        super().__init__(
            file_path=file_path,
            transforms=transforms,
            ase_args=ase_args,
            include_keys=include_keys,
            exclude_keys=exclude_keys,
            key_mapping=key_mapping,
        )

        # Assign unique global atom IDs once at construction
        counter = 0
        for data in self.data_list:
            num_atoms = data[AtomicDataDict.POSITIONS_KEY].shape[0]
            data[_ATOM_ID_KEY] = torch.arange(
                counter,
                counter + num_atoms,
                # ASEDatasetWithGlobalIDs._global_counter,
                # ASEDatasetWithGlobalIDs._global_counter + num_atoms,
                dtype=torch.long,
            )
            counter += num_atoms
            # ASEDatasetWithGlobalIDs._global_counter += num_atoms

        # # Reset in case it gets re-read by other process
        # ASEDatasetWithGlobalIDs._global_counter = 0


class ASEDataModuleWithID(NequIPDataModule):
    """ASEDataModule that assigns atom IDs only once."""

    def __init__(
        self,
        seed: int,
        # file paths
        train_file_path: Optional[Union[str, List[str]]] = None,
        val_file_path: Optional[Union[str, List[str]]] = None,
        test_file_path: Optional[Union[str, List[str]]] = None,
        predict_file_path: Optional[Union[str, List[str]]] = None,
        split_dataset: Optional[Union[Dict, List[Dict]]] = None,
        # data transforms
        transforms: List[Callable] = None,
        # ase params
        ase_args: dict = None,
        include_keys: Optional[List[str]] = None,
        exclude_keys: Optional[List[str]] = None,
        key_mapping: Optional[Dict[str, str]] = None,
        **kwargs,
    ):
        """Initialize."""

        # Set mutable defaults
        if train_file_path is None:
            train_file_path = []

        if val_file_path is None:
            val_file_path = []

        if test_file_path is None:
            test_file_path = []

        if predict_file_path is None:
            predict_file_path = []

        if split_dataset is None:
            split_dataset = []

        if transforms is None:
            transforms = []

        if ase_args is None:
            ase_args = {}

        if include_keys is None:
            include_keys = []

        if exclude_keys is None:
            exclude_keys = []

        if key_mapping is None:
            key_mapping = {}

        # == first convert all dataset paths to lists if not already lists ==
        dataset_paths = []
        for paths in [
                train_file_path,
                val_file_path,
                test_file_path,
                predict_file_path,
                split_dataset,
        ]:
            # convert to primitives as later logic is based on types
            if isinstance(paths, ListConfig) or isinstance(paths, DictConfig):
                paths = OmegaConf.to_container(paths, resolve=True)
            assert (isinstance(paths, list) or isinstance(paths, str)
                    or isinstance(paths, dict))
            if not isinstance(paths, list):
                # convert str -> List[str]
                dataset_paths.append([paths])
            else:
                dataset_paths.append(paths)

        # == assemble config template ==
        dataset_config_template = {
            # "_target_": "nequip.data.dataset.ASEDataset",
            "_target_":
            "orchestrator.potential.nequip_allegro.ASEDatasetWithGlobalIDs",
            "transforms": transforms,
            "ase_args": ase_args,
            "include_keys": include_keys,
            "exclude_keys": exclude_keys,
            "key_mapping": key_mapping,
        }

        # == populate train, val, test predict, split datasets ==
        dataset_configs = [[], [], [], []]
        for config, paths in zip(dataset_configs,
                                 dataset_paths[:-1],
                                 strict=True):
            for path in paths:
                dataset_config = dataset_config_template.copy()
                dataset_config.update({"file_path": path})
                config.append(dataset_config)

        # == populate split dataset ==
        split_config = []
        for path_and_splits in dataset_paths[-1]:
            assert "file_path" in path_and_splits, (
                "`file_path` key must be in each dict of `split_dataset`")
            dataset_config = dataset_config_template.copy()
            file_path = path_and_splits.pop("file_path")
            dataset_config.update({"file_path": file_path})
            path_and_splits.update({"dataset": dataset_config
                                    })  # now actually dataset_and_splits
            split_config.append(path_and_splits)

        super().__init__(
            seed=seed,
            train_dataset=dataset_configs[0],
            val_dataset=dataset_configs[1],
            test_dataset=dataset_configs[2],
            predict_dataset=dataset_configs[3],
            split_dataset=split_config,
            **kwargs,
        )


class LTAULightningModule(EMALightningModule):
    """Custom logging module to record per-sample errors."""

    def __init__(self,
                 *args,
                 error_save_dir: Optional[str] = "force_errors",
                 **kwargs):
        """Initialize."""
        super().__init__(*args, **kwargs)
        self.error_save_dir = error_save_dir
        os.makedirs(self.error_save_dir, exist_ok=True)
        self._error_buffer = None
        self._epoch_force_errors = []  # used in fallback mode

    def setup(self, stage=None):
        """Setup."""
        super().setup(stage)
        if stage != "fit" or self._error_buffer is not None:
            return

        train_ds = self.trainer.datamodule.train_dataset
        datasets = train_ds if isinstance(train_ds, list) else [train_ds]

        all_atom_ids = []
        for ds_list in datasets:
            for ds in ds_list:
                for data in ds:
                    ids = data.get(_ATOM_ID_KEY, None)
                    if ids is not None:
                        all_atom_ids.extend(torch.as_tensor(ids).tolist())

        if not all_atom_ids:
            raise RuntimeError("No atom IDs found in dataset.")

        max_id = max(all_atom_ids)
        self._error_buffer = torch.full((max_id + 1, ), float("nan"))

    def training_step(self, batch, batch_idx, dataloader_idx=0):
        """Run a single training step."""
        target = self.process_target(batch, batch_idx, dataloader_idx)
        output = self(batch)

        if self.train_metrics is not None:
            with torch.no_grad():
                train_metric_dict = self.train_metrics(
                    output,
                    target,
                    prefix=f"train_metric_step{self.logging_delimiter}")
            self.log_dict(train_metric_dict)

        pred_forces = output[AtomicDataDict.FORCE_KEY]
        true_forces = batch[AtomicDataDict.FORCE_KEY]
        per_atom_error = torch.norm(pred_forces - true_forces, dim=-1)

        atom_ids = batch.get(
            _ATOM_ID_KEY,
            torch.arange(per_atom_error.shape[0],
                         device=per_atom_error.device),
        ).long()

        # Write into fixed-size error buffer
        if self._error_buffer is not None:
            atom_ids = atom_ids.detach().cpu()
            errors = per_atom_error.detach().cpu()
            for i, aid in enumerate(atom_ids):
                self._error_buffer[aid] = errors[i]
        else:
            # Fallback if error_buffer wasn't set up
            per_atom_data = torch.stack(
                [atom_ids.detach().to(torch.float32),
                 per_atom_error.detach()],
                dim=1)
            self._epoch_force_errors.append(per_atom_data.cpu())

        loss_dict = self.loss(
            output, target, prefix=f"train_loss_step{self.logging_delimiter}")
        self.log_dict(loss_dict)

        loss = (
            loss_dict[f"train_loss_step{self.logging_delimiter}weighted_sum"]
            * self.world_size)
        return loss

    def on_train_epoch_end(self):
        """Runs at the end of a training epoch."""
        super().on_train_epoch_end()

        if self._error_buffer is not None:
            local_errors = self._error_buffer.to(self.device)
            if is_initialized():
                gathered = [
                    torch.empty_like(local_errors)
                    for _ in range(torch.distributed.get_world_size())
                ]
                torch.distributed.all_gather(gathered, local_errors)
                if self.trainer.is_global_zero:
                    all_errors = torch.stack(gathered, dim=0)
                    # Use the first non-NaN value per atom
                    # final_errors = torch.nanmin(all_errors, dim=0).values
                    final_errors = nanmin_stack(all_errors)
                else:
                    final_errors = None
            else:
                final_errors = local_errors

            if self.trainer.is_global_zero and final_errors is not None:
                epoch = self.trainer.current_epoch
                file_path = os.path.join(
                    self.error_save_dir,
                    f"train_force_errors_epoch_{epoch}.npy")
                np.save(file_path, final_errors.cpu().numpy())

            self._error_buffer[:] = float("nan")

        elif self._epoch_force_errors:
            # fallback mode: gather individual entries
            local_errors = torch.cat(self._epoch_force_errors,
                                     dim=0).to(self.device)

            if is_initialized():
                gathered = [
                    torch.zeros_like(local_errors)
                    for _ in range(torch.distributed.get_world_size())
                ]
                torch.distributed.all_gather(gathered, local_errors)
                if self.trainer.is_global_zero:
                    all_errors = torch.cat(gathered, dim=0)
                else:
                    all_errors = None
            else:
                all_errors = local_errors

            if self.trainer.is_global_zero and all_errors is not None:
                atom_ids = all_errors[:, 0].cpu().numpy()
                assert len(np.unique(atom_ids)) == len(atom_ids), (
                    f"Duplicate atom_ids found: {len(atom_ids)} total vs {len(np.unique(atom_ids))} unique"  # noqa: E501
                )

                sorted_errors = all_errors[all_errors[:, 0].argsort()]
                epoch = self.trainer.current_epoch
                file_path = os.path.join(
                    self.error_save_dir,
                    f"train_force_errors_epoch_{epoch}.npy")
                np.save(file_path, sorted_errors.cpu().numpy())

            self._epoch_force_errors = []


def nanmin_stack(tensors: torch.Tensor) -> torch.Tensor:
    """Compute nanmin across 0th dimension of a stacked tensor (N, M)."""
    valid_mask = ~torch.isnan(tensors)
    masked = torch.where(valid_mask, tensors, float("inf"))
    return torch.min(masked, dim=0).values
